name: swin_transformer
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - absl-py=2.1.0=py310haa95532_0
  - altair=5.5.0=py310haa95532_0
  - arrow-cpp=19.0.0=h82e8c66_4
  - astunparse=1.6.3=py_0
  - aws-c-auth=0.9.0=h827c3e9_1
  - aws-c-cal=0.9.2=h827c3e9_0
  - aws-c-common=0.12.3=h827c3e9_0
  - aws-c-compression=0.3.1=h827c3e9_1
  - aws-c-event-stream=0.5.5=h827c3e9_0
  - aws-c-http=0.10.2=h827c3e9_0
  - aws-c-io=0.20.1=h827c3e9_0
  - aws-c-mqtt=0.13.2=h827c3e9_0
  - aws-c-s3=0.8.3=h827c3e9_0
  - aws-c-sdkutils=0.2.4=h827c3e9_0
  - aws-checksums=0.2.7=h827c3e9_0
  - aws-crt-cpp=0.32.10=h5da7b33_0
  - aws-sdk-cpp=1.11.528=hd293286_1
  - blas=1.0=mkl
  - blinker=1.9.0=py310haa95532_0
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli-python=1.0.9=py310h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.11.4=haa95532_0
  - cachetools=5.5.1=py310haa95532_0
  - certifi=2025.10.5=py310haa95532_0
  - click=8.2.1=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - contourpy=1.3.1=py310h214f63a_0
  - cpuonly=2.0=0
  - deprecated=1.2.13=py310haa95532_0
  - filelock=3.13.1=py310haa95532_0
  - freetype=2.12.1=ha860e81_0
  - gast=0.5.3=pyhd3eb1b0_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - gitdb=4.0.12=py310haa95532_0
  - gitpython=3.1.45=py310haa95532_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.71.0=py310hbb1fe6b_0
  - h5py=3.12.1=py310h535c9fb_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=7.0.1=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h827c3e9_3
  - keras=3.6.0=py310haa95532_0
  - kiwisolver=1.4.8=py310h5da7b33_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.12.1=h9da9810_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=5.29.3=hac4c8cb_0
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.5.1=h44ae7cf_1
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.8=py310haa95532_0
  - markdown-it-py=2.2.0=py310haa95532_1
  - matplotlib-base=3.10.0=py310he19b0ae_0
  - mdurl=0.1.0=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - ml_dtypes=0.5.1=py310h094160a_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - namex=0.0.7=py310haa95532_0
  - narwhals=2.7.0=py310haa95532_0
  - numexpr=2.10.1=py310h4cd664f_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.26.0=py310haa95532_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py310h214f63a_0
  - orc=2.1.1=hd1c1d5c_0
  - packaging=24.2=py310haa95532_0
  - pandas=2.2.3=py310h5da7b33_0
  - pip=25.0=py310haa95532_0
  - protobuf=5.29.3=py310h5da7b33_0
  - pyarrow=19.0.0=py310h885b0b7_2
  - pygments=2.19.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.16=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-flatbuffers=24.3.25=py310haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.5.1=cpu_mkl_py310h0452e45_104
  - pytorch-model-summary=0.1.1=py_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py310h827c3e9_0
  - re2=2024.07.02=h214f63a_0
  - requests=2.32.3=py310haa95532_1
  - rich=13.9.4=py310haa95532_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=75.8.0=py310haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - smmap=5.0.2=py310haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.45.3=h2bbff1b_0
  - streamlit=1.51.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=9.1.2=py310haa95532_0
  - tensorboard=2.18.0=py310haa95532_0
  - tensorboard-data-server=0.7.0=py310haa95532_1
  - tensorflow=2.18.1=cpu_py310h6605a60_0
  - tensorflow-base=2.18.1=cpu_py310h1ab519a_0
  - termcolor=2.1.0=py310haa95532_0
  - tk=8.6.14=h0416ee5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tqdm=4.67.1=py310h9909e9c_0
  - typing-extensions=4.12.2=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py310h827c3e9_1
  - urllib3=2.3.0=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - validators=0.35.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_4
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py310haa95532_0
  - werkzeug=3.1.3=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wrapt=1.17.0=py310h827c3e9_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zipp=3.21.0=py310haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - alembic==1.15.2
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - captum==0.8.0
      - cellpose==4.0.8.dev11+g70c0d07d0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - colorlog==6.9.0
      - comm==0.2.2
      - cycler==0.12.1
      - datasets==3.2.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fastremap==1.17.7
      - fill-voids==2.1.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipympl==0.9.8
      - ipython==8.32.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.16
      - lazy-loader==0.4
      - mako==1.3.9
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nibabel==5.3.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - optuna==4.2.1
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - psutil==6.1.1
      - pure-eval==0.2.3
      - pycparser==2.22
      - pyparsing==3.2.1
      - python-json-logger==3.2.1
      - pytz==2025.1
      - pywin32==308
      - pywinpty==2.0.15
      - pyzmq==26.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - roifile==2025.5.10
      - rpds-py==0.22.3
      - safetensors==0.5.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - segment-anything==1.0
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - timm==1.0.14
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchsummary==1.5.1
      - torchvision==0.20.1+cu121
      - tornado==6.4.2
      - traitlets==5.14.3
      - transformers==4.48.3
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.15
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: C:\Users\sthem\anaconda3\envs\swin_transformer
